=== motclink/OpenLR/map/src/test/resources/openlr/map/mockdb/MockDatabase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="MockedMapDatabase">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Nodes" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="Lines" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="Calls" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Nodes">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="Node"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Node">
        <xs:complexType>
            <xs:all>
                <xs:element ref="Latitude" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="Longitude" minOccurs="1" maxOccurs="1"/>
            </xs:all>
            <xs:attribute name="id" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Lines">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="Line"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Line">
        <xs:complexType>
            <xs:all>
                <xs:element name="FOW" type="xs:NCName" minOccurs="0" maxOccurs="1"/>
                <xs:element name="StartNode" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                <xs:element name="EndNode" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                <xs:element name="FRC" type="xs:NCName" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Length" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            </xs:all>
            <xs:attribute name="id" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Calls">
        <xs:complexType>
            <xs:all>
                <xs:element name="GetPointAlongLineCalls" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="GetPointAlongLine" minOccurs="1"
                                        maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="DistanceToPointCalls" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="DistanceToPoint" minOccurs="1"
                                        maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="MeasureAlongLineCalls" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="MeasureAlongLine" minOccurs="1"
                                        maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="FindNodesCloseByCoordinateCalls"
                            minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="FindNodesCloseByCoordinate"
                                        minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="FindLinesCloseByCoordinateCalls"
                            minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="FindLinesCloseByCoordinate"
                                        minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="GetPointAlongLine">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Input" type="xs:int"/>
                <xs:element name="Output">
                    <xs:complexType>
                        <xs:all>
                            <xs:element ref="Latitude" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="Longitude" minOccurs="1" maxOccurs="1"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="line" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="DistanceToPoint">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Input">
                    <xs:complexType>
                        <xs:all>
                            <xs:element ref="Latitude" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="Longitude" minOccurs="1" maxOccurs="1"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Output" type="xs:int"/>
            </xs:sequence>
            <xs:attribute name="line" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="MeasureAlongLine">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Input">
                    <xs:complexType>
                        <xs:all>
                            <xs:element ref="Latitude" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="Longitude" minOccurs="1" maxOccurs="1"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Output" type="xs:int"/>
            </xs:sequence>
            <xs:attribute name="line" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="FindNodesCloseByCoordinate">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Input">
                    <xs:complexType>
                        <xs:all>
                            <xs:element ref="Latitude" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="Longitude" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="Distance" type="xs:int"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Output">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Node" type="xs:long" minOccurs="1"
                                        maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="FindLinesCloseByCoordinate">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Input">
                    <xs:complexType>
                        <xs:all>
                            <xs:element ref="Latitude" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="Longitude" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="Distance" type="xs:int"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Output">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Line" type="xs:long" minOccurs="1"
                                        maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Latitude" type="xs:double"/>
    <xs:element name="Longitude" type="xs:double"/>

</xs:schema>

=== motclink/OpenLR/encoder/src/test/resources/LongPathExtensionBackwards.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (C) 2009-2019 TomTom International B.V. TomTom (Legal Department)
	Email: legal@tomtom.com TomTom (Technical contact) Email: openlr@tomtom.com 
	Address: TomTom International B.V., Oosterdoksstraat 114, 1011DK Amsterdam, 
	the Netherlands This program is free software; you can redistribute it and/or 
	modify it under the terms of the GNU General Public License as published 
	by the Free Software Foundation; version 2 of the License and the extra conditions 
	for OpenLR. (see openlr-license.txt) This program is distributed in the hope 
	that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
	warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
	GNU General Public License for more details. You should have received a copy 
	of the GNU General Public License along with this program; if not, write 
	to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, 
	MA 02110-1301 USA. -->
<MockedMapDatabase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="openlr/map/mockdb/MockDatabase.xsd">
    <Nodes>
        <Node id="1">
            <Latitude>49.60315</Latitude>
            <Longitude>6.272792</Longitude>
        </Node>
        <Node id="2">
            <Latitude>49.600315</Latitude>
            <Longitude>6.316112</Longitude>
        </Node>
        <Node id="3">
            <Latitude>49.600315</Latitude>
            <Longitude>6.409</Longitude>
        </Node>

        <Node id="4">
            <Latitude>49.600315</Latitude>
            <Longitude>6.409211</Longitude>
        </Node>


        <Node id="5">
            <Latitude>49.600315</Latitude>
            <Longitude>6.484729</Longitude>
        </Node>
        <Node id="6">
            <Latitude>49.600315</Latitude>
            <Longitude>6.485</Longitude>
        </Node>
    </Nodes>

    <Lines>
        <Line id="1">
            <StartNode>1</StartNode>
            <EndNode>2</EndNode>
            <Length>200</Length>
            <FRC>FRC_5</FRC>
        </Line>
        <Line id="2">
            <StartNode>2</StartNode>
            <EndNode>3</EndNode>
            <Length>15000</Length>
            <FRC>FRC_5</FRC>
        </Line>
        <Line id="3">
            <StartNode>3</StartNode>
            <EndNode>4</EndNode>
            <Length>200</Length>
            <FRC>FRC_5</FRC>
        </Line>
        <Line id="4">
            <StartNode>4</StartNode>
            <EndNode>5</EndNode>
            <Length>14800</Length>
            <FRC>FRC_5</FRC>
        </Line>
        <Line id="5">
            <StartNode>5</StartNode>
            <EndNode>6</EndNode>
            <Length>200</Length>
            <FRC>FRC_5</FRC>
        </Line>
    </Lines>

    <Calls>
        <GetPointAlongLineCalls>
            <GetPointAlongLine line="3">
                <Input>180</Input>
                <Output>
                    <Latitude>49.600315</Latitude>
                    <Longitude>6.40918</Longitude>
                </Output>
            </GetPointAlongLine>
            <GetPointAlongLine line="3">
                <Input>20</Input>
                <Output>
                    <Latitude>49.600315</Latitude>
                    <Longitude>6.31786</Longitude>
                </Output>
            </GetPointAlongLine>
            <GetPointAlongLine line="2">
                <Input>20</Input>
                <Output>
                    <Latitude>49.600315</Latitude>
                    <Longitude>6.3162</Longitude>
                </Output>
            </GetPointAlongLine>
            <GetPointAlongLine line="5">
                <Input>180</Input>
                <Output>
                    <Latitude>49.600315</Latitude>
                    <Longitude>6.4080</Longitude>
                </Output>
            </GetPointAlongLine>
            <GetPointAlongLine line="5">
                <Input>20</Input>
                <Output>
                    <Latitude>49.600315</Latitude>
                    <Longitude>6.4102</Longitude>
                </Output>
            </GetPointAlongLine>
            <GetPointAlongLine line="5">
                <Input>199</Input>
                <Output>
                    <Latitude>49.600315</Latitude>
                    <Longitude>6.4845</Longitude>
                </Output>
            </GetPointAlongLine>
            <GetPointAlongLine line="4">
                <Input>20</Input>
                <Output>
                    <Latitude>49.600315</Latitude>
                    <Longitude>6.40922</Longitude>
                </Output>
            </GetPointAlongLine>
            <GetPointAlongLine line="4">
                <Input>14780</Input>
                <Output>
                    <Latitude>49.600315</Latitude>
                    <Longitude>6.41</Longitude>
                </Output>
            </GetPointAlongLine>
        </GetPointAlongLineCalls>
        <MeasureAlongLineCalls>
            <MeasureAlongLine line="1">
                <Input>
                    <Longitude>6.12806</Longitude>
                    <Latitude>49.60302</Latitude>
                </Input>
                <Output>15000</Output>
            </MeasureAlongLine>
        </MeasureAlongLineCalls>
    </Calls>
</MockedMapDatabase>
