=== motclink/OpenLR/map/src/test/resources/openlr/map/mockdb/MockDatabase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="MockedMapDatabase">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Nodes" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="Lines" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="Calls" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Nodes">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="Node"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Node">
        <xs:complexType>
            <xs:all>
                <xs:element ref="Latitude" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="Longitude" minOccurs="1" maxOccurs="1"/>
            </xs:all>
            <xs:attribute name="id" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Lines">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="Line"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Line">
        <xs:complexType>
            <xs:all>
                <xs:element name="FOW" type="xs:NCName" minOccurs="0" maxOccurs="1"/>
                <xs:element name="StartNode" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                <xs:element name="EndNode" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                <xs:element name="FRC" type="xs:NCName" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Length" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            </xs:all>
            <xs:attribute name="id" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Calls">
        <xs:complexType>
            <xs:all>
                <xs:element name="GetPointAlongLineCalls" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="GetPointAlongLine" minOccurs="1"
                                        maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="DistanceToPointCalls" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="DistanceToPoint" minOccurs="1"
                                        maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="MeasureAlongLineCalls" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="MeasureAlongLine" minOccurs="1"
                                        maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="FindNodesCloseByCoordinateCalls"
                            minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="FindNodesCloseByCoordinate"
                                        minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="FindLinesCloseByCoordinateCalls"
                            minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="FindLinesCloseByCoordinate"
                                        minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:element name="GetPointAlongLine">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Input" type="xs:int"/>
                <xs:element name="Output">
                    <xs:complexType>
                        <xs:all>
                            <xs:element ref="Latitude" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="Longitude" minOccurs="1" maxOccurs="1"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="line" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="DistanceToPoint">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Input">
                    <xs:complexType>
                        <xs:all>
                            <xs:element ref="Latitude" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="Longitude" minOccurs="1" maxOccurs="1"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Output" type="xs:int"/>
            </xs:sequence>
            <xs:attribute name="line" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="MeasureAlongLine">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Input">
                    <xs:complexType>
                        <xs:all>
                            <xs:element ref="Latitude" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="Longitude" minOccurs="1" maxOccurs="1"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Output" type="xs:int"/>
            </xs:sequence>
            <xs:attribute name="line" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="FindNodesCloseByCoordinate">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Input">
                    <xs:complexType>
                        <xs:all>
                            <xs:element ref="Latitude" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="Longitude" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="Distance" type="xs:int"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Output">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Node" type="xs:long" minOccurs="1"
                                        maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="FindLinesCloseByCoordinate">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Input">
                    <xs:complexType>
                        <xs:all>
                            <xs:element ref="Latitude" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="Longitude" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="Distance" type="xs:int"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Output">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Line" type="xs:long" minOccurs="1"
                                        maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Latitude" type="xs:double"/>
    <xs:element name="Longitude" type="xs:double"/>

</xs:schema>

=== motclink/OpenLR/encoder/src/test/resources/ExtraLongLineMapAndExtension.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (C) 2009-2019 TomTom International B.V. TomTom (Legal Department)
    Email: legal@tomtom.com TomTom (Technical contact) Email:
    openlr@tomtom.com Address: TomTom International B.V., Oosterdoksstraat
    114, 1011DK Amsterdam, the Netherlands This program is free software;
    you can redistribute it and/or modify it under the terms of the GNU
    General Public License as published by the Free Software Foundation;
    version 2 of the License and the extra conditions for OpenLR. (see
    openlr-license.txt) This program is distributed in the hope that it
    will be useful, but WITHOUT ANY WARRANTY; without even the implied
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See
    the GNU General Public License for more details. You should have
    received a copy of the GNU General Public License along with this
    program; if not, write to the Free Software Foundation, Inc., 51
    Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
-->
<MockedMapDatabase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="openlr/map/mockdb/MockDatabase.xsd">
    <Nodes>
        <Node id="1">
            <Latitude>49.60315</Latitude>
            <Longitude>6.12786</Longitude>
        </Node>
        <Node id="2">
            <Latitude>49.60305</Latitude>
            <Longitude>6.12817</Longitude>
        </Node>
        <Node id="3">
            <Latitude>49.69423</Latitude>
            <Longitude>6.31762</Longitude>
        </Node>
        <Node id="4">
            <Latitude>49.7057</Latitude>
            <Longitude>6.33596</Longitude>
        </Node>
        <Node id="5">
            <Latitude>50.93869</Latitude>
            <Longitude>8.66343</Longitude>
        </Node>
    </Nodes>

    <Lines>
        <Line id="1">
            <StartNode>1</StartNode>
            <EndNode>2</EndNode>
            <Length>23000</Length>
            <FRC>FRC_5</FRC>
        </Line>
        <Line id="2">
            <StartNode>2</StartNode>
            <EndNode>3</EndNode>
            <Length>725</Length>
            <FRC>FRC_5</FRC>
        </Line>
        <Line id="3">
            <StartNode>3</StartNode>
            <EndNode>4</EndNode>
            <Length>1200</Length>
            <FRC>FRC_5</FRC>
        </Line>
        <Line id="4">
            <StartNode>4</StartNode>
            <EndNode>5</EndNode>
            <Length>5200</Length>
            <FRC>FRC_1</FRC>
        </Line>
    </Lines>

    <Calls>
        <GetPointAlongLineCalls>
            <GetPointAlongLine line="1">
                <Input>20</Input>
                <Output>
                    <Longitude>6.12806</Longitude>
                    <Latitude>49.60302</Latitude>
                </Output>
            </GetPointAlongLine>
            <GetPointAlongLine line="1">
                <Input>22980</Input>
                <Output>
                    <Longitude>6.12806</Longitude>
                    <Latitude>49.60302</Latitude>
                </Output>
            </GetPointAlongLine>
            <GetPointAlongLine line="2">
                <Input>20</Input>
                <Output>
                    <Longitude>6.12806</Longitude>
                    <Latitude>49.60302</Latitude>
                </Output>
            </GetPointAlongLine>
            <GetPointAlongLine line="1">
                <Input>3200</Input>
                <Output>
                    <Longitude>6.12806</Longitude>
                    <Latitude>49.60302</Latitude>
                </Output>
            </GetPointAlongLine>

            <GetPointAlongLine line="1">
                <Input>15000</Input>
                <Output>
                    <Longitude>6.12806</Longitude>
                    <Latitude>49.60302</Latitude>
                </Output>
            </GetPointAlongLine>
            <GetPointAlongLine line="1">
                <Input>14980</Input>
                <Output>
                    <Longitude>6.12806</Longitude>
                    <Latitude>49.60302</Latitude>
                </Output>
            </GetPointAlongLine>

            <GetPointAlongLine line="1">
                <Input>15020</Input>
                <Output>
                    <Longitude>6.12807</Longitude>
                    <Latitude>49.60302</Latitude>
                </Output>
            </GetPointAlongLine>

            <GetPointAlongLine line="3">
                <Input>1180</Input>
                <Output>
                    <Longitude>6.12806</Longitude>
                    <Latitude>49.60302</Latitude>
                </Output>
            </GetPointAlongLine>
            <GetPointAlongLine line="4">
                <Input>5180</Input>
                <Output>
                    <Longitude>6.12806</Longitude>
                    <Latitude>49.60302</Latitude>
                </Output>
            </GetPointAlongLine>

            <GetPointAlongLine line="4">
                <Input>20</Input>
                <Output>
                    <Longitude>6.12806</Longitude>
                    <Latitude>49.60303</Latitude>
                </Output>
            </GetPointAlongLine>

            <GetPointAlongLine line="4">
                <Input>15000</Input>
                <Output>
                    <Longitude>6.12807</Longitude>
                    <Latitude>49.60304</Latitude>
                </Output>
            </GetPointAlongLine>

            <GetPointAlongLine line="4">
                <Input>1200</Input>
                <Output>
                    <Longitude>6.12807</Longitude>
                    <Latitude>49.60304</Latitude>
                </Output>
            </GetPointAlongLine>

            <GetPointAlongLine line="4">
                <Input>1220</Input>
                <Output>
                    <Longitude>6.12807</Longitude>
                    <Latitude>49.60304</Latitude>
                </Output>
            </GetPointAlongLine>

        </GetPointAlongLineCalls>

        <MeasureAlongLineCalls>
            <MeasureAlongLine line="1">
                <Output>15000</Output>
                <Input>
                    <Longitude>6.12806</Longitude>
                    <Latitude>49.60302</Latitude>
                </Input>
            </MeasureAlongLine>

            <MeasureAlongLine line="4">
                <Output>1200</Output>
                <Input>
                    <Longitude>6.12807</Longitude>
                    <Latitude>49.60304</Latitude>
                </Input>
            </MeasureAlongLine>
        </MeasureAlongLineCalls>
    </Calls>
</MockedMapDatabase>

=== motclink/OpenLR/decoder/src/test/resources/PointAlongLineDecoderMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (C) 2009-2019 TomTom International B.V. TomTom (Legal Department)
	Email: legal@tomtom.com TomTom (Technical contact) Email: openlr@tomtom.com 
	Address: TomTom International B.V., Oosterdoksstraat 114, 1011DK Amsterdam, 
	the Netherlands This program is free software; you can redistribute it and/or 
	modify it under the terms of the GNU General Public License as published 
	by the Free Software Foundation; version 2 of the License and the extra conditions 
	for OpenLR. (see openlr-license.txt) This program is distributed in the hope 
	that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
	warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
	GNU General Public License for more details. You should have received a copy 
	of the GNU General Public License along with this program; if not, write 
	to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, 
	MA 02110-1301 USA. -->
<MockedMapDatabase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="openlr/map/mockdb/MockDatabase.xsd">
    <Nodes>
        <Node id="1">
            <Latitude>51.663090</Latitude>
            <Longitude>10.856862</Longitude>
        </Node>
        <Node id="2">
            <Latitude>51.663213</Latitude>
            <Longitude>11.002753</Longitude>
        </Node>
    </Nodes>
    <Lines>
        <Line id="1">
            <StartNode>1</StartNode>
            <EndNode>2</EndNode>
            <Length>10000</Length>
            <FRC>FRC_0</FRC>
            <FOW>MOTORWAY</FOW>
        </Line>
    </Lines>
    <Calls>
        <GetPointAlongLineCalls>

            <GetPointAlongLine line="1">
                <Input>2000</Input>
                <Output>
                    <Longitude>10.887121</Longitude>
                    <Latitude>51.663269</Latitude>
                </Output>
            </GetPointAlongLine>

            <GetPointAlongLine line="1">
                <Input>2020</Input>
                <Output>
                    <Longitude>10.887125</Longitude>
                    <Latitude>51.663269</Latitude>
                </Output>
            </GetPointAlongLine>

            <GetPointAlongLine line="1">
                <Input>7000</Input>
                <Output>
                    <Longitude>10.958748</Longitude>
                    <Latitude>51.663104</Latitude>
                </Output>
            </GetPointAlongLine>

            <GetPointAlongLine line="1">
                <Input>6980</Input>
                <Output>
                    <Longitude>10.958742</Longitude>
                    <Latitude>51.663104</Latitude>
                </Output>
            </GetPointAlongLine>

            <GetPointAlongLine line="1">
                <Input>3000</Input>
                <Output>
                    <Longitude>10.0</Longitude>
                    <Latitude>51.0</Latitude>
                </Output>
            </GetPointAlongLine>

        </GetPointAlongLineCalls>

        <DistanceToPointCalls>
            <DistanceToPoint line="1">
                <Input>
                    <Longitude>10.887121</Longitude>
                    <Latitude>51.663269</Latitude>
                </Input>
                <Output>
                    0
                </Output>
            </DistanceToPoint>

            <DistanceToPoint line="1">
                <Input>
                    <Longitude>10.958748</Longitude>
                    <Latitude>51.663104</Latitude>
                </Input>
                <Output>
                    0
                </Output>
            </DistanceToPoint>

        </DistanceToPointCalls>

        <MeasureAlongLineCalls>
            <MeasureAlongLine line="1">
                <Input>
                    <Longitude>10.887121</Longitude>
                    <Latitude>51.663269</Latitude>
                </Input>
                <Output>
                    2000
                </Output>
            </MeasureAlongLine>

            <MeasureAlongLine line="1">
                <Input>
                    <Longitude>10.958748</Longitude>
                    <Latitude>51.663104</Latitude>
                </Input>
                <Output>
                    7000
                </Output>
            </MeasureAlongLine>

        </MeasureAlongLineCalls>
        <FindNodesCloseByCoordinateCalls>

            <FindNodesCloseByCoordinate>
                <Input>
                    <Longitude>10.887121</Longitude>
                    <Latitude>51.663269</Latitude>
                    <Distance>100</Distance>
                </Input>
                <Output>
                </Output>
            </FindNodesCloseByCoordinate>

            <FindNodesCloseByCoordinate>
                <Input>
                    <Longitude>10.958748</Longitude>
                    <Latitude>51.663104</Latitude>
                    <Distance>100</Distance>
                </Input>
                <Output>
                </Output>
            </FindNodesCloseByCoordinate>

        </FindNodesCloseByCoordinateCalls>

        <FindLinesCloseByCoordinateCalls>
            <FindLinesCloseByCoordinate>
                <Input>
                    <Longitude>10.887121</Longitude>
                    <Latitude>51.663269</Latitude>
                    <Distance>100</Distance>
                </Input>
                <Output>
                    <Line>1</Line>
                </Output>
            </FindLinesCloseByCoordinate>

            <FindLinesCloseByCoordinate>
                <Input>
                    <Longitude>10.958748</Longitude>
                    <Latitude>51.663104</Latitude>
                    <Distance>100</Distance>
                </Input>
                <Output>
                    <Line>1</Line>
                </Output>
            </FindLinesCloseByCoordinate>

        </FindLinesCloseByCoordinateCalls>
    </Calls>
</MockedMapDatabase>

=== motclink/OpenLR/encoder/src/test/resources/ParallelRoadsMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (C) 2009-2019 TomTom International B.V. TomTom (Legal Department)
    Email: legal@tomtom.com TomTom (Technical contact) Email:
    openlr@tomtom.com Address: TomTom International B.V., Oosterdoksstraat
    114, 1011DK Amsterdam, the Netherlands This program is free software;
    you can redistribute it and/or modify it under the terms of the GNU
    General Public License as published by the Free Software Foundation;
    version 2 of the License and the extra conditions for OpenLR. (see
    openlr-license.txt) This program is distributed in the hope that it
    will be useful, but WITHOUT ANY WARRANTY; without even the implied
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See
    the GNU General Public License for more details. You should have
    received a copy of the GNU General Public License along with this
    program; if not, write to the Free Software Foundation, Inc., 51
    Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
-->
<MockedMapDatabase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="openlr/map/mockdb/MockDatabase.xsd">
    <Nodes>
        <Node id="1">
            <Latitude>40.75629</Latitude>
            <Longitude>-73.96526</Longitude>
        </Node>
        <Node id="2">
            <Latitude>40.75702</Latitude>
            <Longitude>-73.96696</Longitude>
        </Node>
        <Node id="3">
            <Latitude>40.75797</Latitude>
            <Longitude>-73.96922</Longitude>
        </Node>
        <Node id="4">
            <Latitude>40.75862</Latitude>
            <Longitude>-73.97080</Longitude>
        </Node>
    </Nodes>
    <Lines>
        <Line id="1">
            <StartNode>1</StartNode>
            <EndNode>2</EndNode>
            <Length>500</Length>
            <FRC>FRC_5</FRC>
            <FOW>MULTIPLE_CARRIAGEWAY</FOW>
        </Line>
        <Line id="-1">
            <StartNode>2</StartNode>
            <EndNode>1</EndNode>
            <Length>500</Length>
            <FRC>FRC_5</FRC>
            <FOW>MULTIPLE_CARRIAGEWAY</FOW>
        </Line>
        <Line id="2">
            <StartNode>2</StartNode>
            <EndNode>3</EndNode>
            <Length>750</Length>
            <FRC>FRC_5</FRC>
            <FOW>MULTIPLE_CARRIAGEWAY</FOW>
        </Line>
        <Line id="-2">
            <StartNode>3</StartNode>
            <EndNode>2</EndNode>
            <Length>750</Length>
            <FRC>FRC_5</FRC>
            <FOW>MULTIPLE_CARRIAGEWAY</FOW>
        </Line>
        <Line id="3">
            <StartNode>3</StartNode>
            <EndNode>4</EndNode>
            <Length>550</Length>
            <FRC>FRC_5</FRC>
            <FOW>MULTIPLE_CARRIAGEWAY</FOW>
        </Line>
        <Line id="-3">
            <StartNode>4</StartNode>
            <EndNode>3</EndNode>
            <Length>550</Length>
            <FRC>FRC_5</FRC>
            <FOW>MULTIPLE_CARRIAGEWAY</FOW>
        </Line>
        <Line id="4">
            <StartNode>3</StartNode>
            <EndNode>2</EndNode>
            <Length>800</Length>
            <FRC>FRC_5</FRC>
            <FOW>MULTIPLE_CARRIAGEWAY</FOW>
        </Line>
        <Line id="-4">
            <StartNode>2</StartNode>
            <EndNode>3</EndNode>
            <Length>800</Length>
            <FRC>FRC_5</FRC>
            <FOW>MULTIPLE_CARRIAGEWAY</FOW>
        </Line>
    </Lines>
    <Calls>
        <GetPointAlongLineCalls>
            <GetPointAlongLine line="1">
                <Input>20</Input>
                <Output>
                    <Longitude>-73.96548</Longitude>
                    <Latitude>40.75632</Latitude>
                </Output>
            </GetPointAlongLine>
            <GetPointAlongLine line="3">
                <Input>530</Input>
                <Output>
                    <Longitude>-73.97064</Longitude>
                    <Latitude>40.75852</Latitude>
                </Output>
            </GetPointAlongLine>
            <GetPointAlongLine line="2">
                <Input>20</Input>
                <Output>
                    <Longitude>-73.96699</Longitude>
                    <Latitude>40.7572</Latitude>
                </Output>
            </GetPointAlongLine>
            <GetPointAlongLine line="2">
                <Input>730</Input>
                <Output>
                    <Longitude>-73.96894</Longitude>
                    <Latitude>40.75796</Latitude>
                </Output>
            </GetPointAlongLine>
        </GetPointAlongLineCalls>
    </Calls>
</MockedMapDatabase>
